title: Leehyunsuck GitHub Blog
description: > # this means to ignore newlines until "baseurl:"
  Existing project descriptions and various information are posted here.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog        /flexible-jekyll
url: "https://leehyunsuck.github.io/"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Lee Hyunsuck
author-img: leehyunsuck.jpg # assets/img
about-author: 구현됨에 재미를 느끼는 신입 개발자 이현석 입니다. # add description
social-twitter: # add your Twitter handle 제거
social-facebook: # add your Facebook handle 제거
social-github: leehyunsuck # add your Github handle
social-linkedin: leehyunsuck/ # add your Linkedin handle
social-email: leehyunsuck01@gmail.com # add your Email address

# Disqus
discus-identifier: leehyunsuck01 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
